baseURL = '/'
languageCode = 'ru'
title = 'Over Docs'
canonifyURLs = true

paginate = 0


[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noHl = true
    style = "monokai"